In this project, we are going to contribute to the development of a mobile app that is meant to help lottery addicts better estimate their chances of winning.

Many people start playing the lottery for fun, but for some this activity turns into a habit which eventually escalates into addiction. Like other compulsive gamblers, lottery addicts soon begin spending from their savings and loans, they start to accumulate debts, and eventually engage in desperate behaviors like theft.

A medical institute that aims to prevent and treat gambling addictions wants to build a dedicated mobile app to help lottery addicts better estimate their chances of winning. The institute has a team of engineers that will build the app, but they need us to create the logical core of the app and calculate probabilities.

For the first version of the app, they want us to focus on the 6/49 lottery and build functions that enable users to get answers to questions like:
* What is the probability of winning the big prize with a single ticket?
* What is the probability of winning the big prize if we play 40 different tickets (or any other number)?
* What is the probability of having at least five (or four, or three, or two) winning numbers on a single ticket?

The institute also wants us to consider historical data coming from the national 6/49 lottery game in Canada. The data set has data for 3,665 drawings, dating from 1982 to 2018.

In [1]:
import numpy as np
import pandas as pd
import re

# Core Functions

In the 6/49 lottery, six numbers are drawn from a set of 49 numbers that range from 1 to 49. The drawing is done without replacement, which means once a number is drawn, it's not put back in the set.

In [2]:
#computes factorial of a number n
def factorial(n):
    if n != 1:
        return n * factorial(n-1)
    else:
        return 1
    
# find the number of combinations when we're sampling without replacement and taking only k objects from a group of n objects
def combinations(n,k):
    return factorial(n) / (factorial(n-k) * factorial(k))

# One-ticket Probability

A player wins the big prize if the six numbers on their tickets match all the six numbers drawn.
* If a player has a ticket with the numbers {13, 22, 24, 27, 42, 44}, he only wins the big prize if the numbers drawn are {13, 22, 24, 27, 42, 44}. If only one number differs, he doesn't win.

For the first version of the app, we want players to be able to calculate the probability of winning the big prize with the various numbers they play on a single ticket (for each ticket a player chooses six numbers out of 49). So, we'll start by building a function that calculates the probability of winning the big prize for any given ticket.

In [3]:
def one_ticket_probability(ticket_numbers):
    number_of_successful_outcomes = 1
    number_of_possible_outcomes = combinations(49,6)
    big_prize_win_probability = number_of_successful_outcomes / number_of_possible_outcomes
    probability_pct = big_prize_win_probability * 100
    print('''The chance of winning the big prize with the numbers {} on your ticket is : {:.7f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(ticket_numbers,probability_pct,int(number_of_possible_outcomes)))

In [4]:
one_ticket_probability([34,41,2,30,15,23])

The chance of winning the big prize with the numbers [34, 41, 2, 30, 15, 23] on your ticket is : 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


# Historical Data Check for Canada Lottery

In [5]:
historical_lottery_data = pd.read_csv('649.csv')
historical_lottery_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   PRODUCT          3665 non-null   int64 
 1   DRAW NUMBER      3665 non-null   int64 
 2   SEQUENCE NUMBER  3665 non-null   int64 
 3   DRAW DATE        3665 non-null   object
 4   NUMBER DRAWN 1   3665 non-null   int64 
 5   NUMBER DRAWN 2   3665 non-null   int64 
 6   NUMBER DRAWN 3   3665 non-null   int64 
 7   NUMBER DRAWN 4   3665 non-null   int64 
 8   NUMBER DRAWN 5   3665 non-null   int64 
 9   NUMBER DRAWN 6   3665 non-null   int64 
 10  BONUS NUMBER     3665 non-null   int64 
dtypes: int64(10), object(1)
memory usage: 315.1+ KB


The institute also wants us to consider the data coming from the national 6/49 lottery game in Canada. The data set contains historical data for 3,665 drawings, dating from 1982 to 2018 

In [6]:
historical_lottery_data

PRODUCT  DRAW NUMBER  SEQUENCE NUMBER  DRAW DATE  NUMBER DRAWN 1  \
0         649            1                0  6/12/1982               3   
1         649            2                0  6/19/1982               8   
2         649            3                0  6/26/1982               1   
3         649            4                0   7/3/1982               3   
4         649            5                0  7/10/1982               5   
...       ...          ...              ...        ...             ...   
3660      649         3587                0   6/6/2018              10   
3661      649         3588                0   6/9/2018              19   
3662      649         3589                0  6/13/2018               6   
3663      649         3590                0  6/16/2018               2   
3664      649         3591                0  6/20/2018              14   

      NUMBER DRAWN 2  NUMBER DRAWN 3  NUMBER DRAWN 4  NUMBER DRAWN 5  \
0                 11              12              14              41   
1                 33              36              37              39   
2                  6              23              24              27   
3                  9              10              13              20   
4                 14              21              31              34   
...              ...             ...             ...             ...   
3660              15              23              38              40   
3661              25              31              36              46   
3662              22              24              31              32   
3663              15              21              31              38   
3664              24              31              35              37   

      NUMBER DRAWN 6  BONUS NUMBER  
0                 43            13  
1                 41             9  
2                 39            34  
3                 43            34  
4                 47            45  
...              ...           ...  
3660              41            35  
3661              47            26  
3662              34            16  
3663              49             8  
3664              48            17  

[3665 rows x 11 columns]

# Function for Historical Data Check

For the first version of the app, however, users should also be able to compare their ticket against the historical lottery data in Canada and determine whether they would have ever won by now.

The engineering team told us that we need to be aware of the following details:

* Inside the app, the user inputs six different numbers from 1 to 49.
* Under the hood, the six numbers will come as a Python list and serve as an input to our function.
* The engineering team wants us to write a function that prints:
    - the number of times the combination selected occurred in the Canada data set; and
    - the probability of winning the big prize in the next drawing with that combination.

Hence will accomplish this below:-

In [7]:
numbers_drawn_on_ticket_columns = [col for col in historical_lottery_data.columns if re.search(r'^NUMBER DRAWN',col)]
numbers_drawn_on_ticket_columns

['NUMBER DRAWN 1',
 'NUMBER DRAWN 2',
 'NUMBER DRAWN 3',
 'NUMBER DRAWN 4',
 'NUMBER DRAWN 5',
 'NUMBER DRAWN 6']

In [8]:
def extract_numbers(drawing):
    ticket_numbers = set(drawing[numbers_drawn_on_ticket_columns])
    return ticket_numbers

historical_lottery_data_ticket_numbers = historical_lottery_data.apply(extract_numbers,axis=1)
historical_lottery_data_ticket_numbers

0        {3, 41, 11, 12, 43, 14}
1        {33, 36, 37, 39, 8, 41}
2         {1, 6, 39, 23, 24, 27}
3         {3, 9, 10, 43, 13, 20}
4        {34, 5, 14, 47, 21, 31}
                  ...           
3660    {38, 40, 41, 10, 15, 23}
3661    {36, 46, 47, 19, 25, 31}
3662     {32, 34, 6, 22, 24, 31}
3663     {2, 38, 15, 49, 21, 31}
3664    {35, 37, 14, 48, 24, 31}
Length: 3665, dtype: object

In [9]:
def check_historical_occurence(user_ticket):
    user_ticket_numbers = set(user_ticket)
    number_of_historical_occurences = (user_ticket_numbers == historical_lottery_data_ticket_numbers).sum()
    #based on historical data:
    #user_ticket_winning_probability = number_of_historical_occurences/historical_lottery_data_ticket_numbers.size
    #user_ticket_winning_probability_pct = user_ticket_winning_probability*100
    if number_of_historical_occurences == 0:
        print('''The combination {} has never occured
This doesn't mean it's more likely to occur now. Your chances to win the big prize in the next drawing using the combination {} are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.'''.format(user_ticket,user_ticket))
    else:
        print('''For the numbers {} in the combination you chose, such a combination has occured in past {} times.
Your chances to win the big prize in the next drawing using the combination {} are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.
'''.format(user_ticket,number_of_historical_occurences,user_ticket))        

In [10]:
#testing the function
test_input_1 = [1,6,39,23,24,27]
check_historical_occurence(test_input_1)

For the numbers [1, 6, 39, 23, 24, 27] in the combination you chose, such a combination has occured in past 1 times.
Your chances to win the big prize in the next drawing using the combination [1, 6, 39, 23, 24, 27] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.



In [11]:
test_input_2 = [2,34,5,8,42,36]
check_historical_occurence(test_input_2)

The combination [2, 34, 5, 8, 42, 36] has never occured
This doesn't mean it's more likely to occur now. Your chances to win the big prize in the next drawing using the combination [2, 34, 5, 8, 42, 36] are 0.0000072%.
In other words, you have a 1 in 13,983,816 chances to win.


# Multi-ticket Probability

For the first version of the app, users should also be able to find the probability of winning if they play multiple different tickets. For instance, someone might intend to play 15 different tickets and they want to know the probability of winning the big prize.

The engineering team wants us to be aware of the following details when we're writing the function:
* The user will input the number of different tickets they want to play (without inputting the specific combinations they intend to play).
* Our function will see an integer between 1 and 13,983,816 (the maximum number of different tickets).
* The function should print information about the probability of winning the big prize depending on the number of different tickets played.

In [12]:
number_of_different_tickets_possible = combinations(49,6)
number_of_different_tickets_possible

13983816.0

In [13]:
def multi_ticket_probability(number_of_tickets_to_play):
    number_of_successful_outcomes = number_of_tickets_to_play
    total_number_of_outcomes = number_of_different_tickets_possible
    multi_ticket_play_probability = number_of_successful_outcomes / total_number_of_outcomes
    multi_ticket_play_probability_pct = multi_ticket_play_probability * 100
    if number_of_tickets_to_play == 1:
        print('''Your chances to win the big prize with one ticket are {:.6f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(multi_ticket_play_probability_pct,int(number_of_different_tickets_possible)))
    else:
        combinations_simplfied = round(total_number_of_outcomes/number_of_successful_outcomes)
        print('''Your chances to win the big prize with {:,} different tickets are {:.6f}%.
In other words, you have a 1 in {:,} chances to win.'''.format(number_of_tickets_to_play,multi_ticket_play_probability_pct,combinations_simplfied))

In [14]:
#testing the function
test_inputs = [1, 10, 100, 10000, 1000000, 6991908, 13983816]
for test_input in test_inputs:
    multi_ticket_probability(test_input)
    print('------------------------')

Your chances to win the big prize with one ticket are 0.000007%.
In other words, you have a 1 in 13,983,816 chances to win.
------------------------
Your chances to win the big prize with 10 different tickets are 0.000072%.
In other words, you have a 1 in 1,398,382 chances to win.
------------------------
Your chances to win the big prize with 100 different tickets are 0.000715%.
In other words, you have a 1 in 139,838 chances to win.
------------------------
Your chances to win the big prize with 10,000 different tickets are 0.071511%.
In other words, you have a 1 in 1,398 chances to win.
------------------------
Your chances to win the big prize with 1,000,000 different tickets are 7.151124%.
In other words, you have a 1 in 14 chances to win.
------------------------
Your chances to win the big prize with 6,991,908 different tickets are 50.000000%.
In other words, you have a 1 in 2 chances to win.
------------------------
Your chances to win the big prize with 13,983,816 different ti

#  Less Winning Numbers — Function

In most 6/49 lotteries there are smaller prizes if a player's ticket match two, three, four, or five of the six numbers drawn. As a consequence, the users might be interested in knowing the probability of having two, three, four, or five winning numbers.

These are the engineering details we'll need to be aware of:
* Inside the app, the user inputs:
    - six different numbers from 1 to 49; and
    - an integer between 2 and 5 that represents the number of winning numbers expected
* Our function prints information about the probability of having the inputted number of winning numbers.

To calculate the probabilities, we tell the engineering team that the specific combination on the ticket is irrelevant behind the scenes, and we only need the integer between 2 and 5 representing the number of winning numbers expected. Consequently, we will write a function named `probability_less_6()` which takes in an integer and prints information about the chances of the user's ticket exactly matching the given number of winning numbers.

In [15]:
def probability_less_6(expected_number_of_winning_numbers):
    number_of_sucessful_outcomes = combinations(6,expected_number_of_winning_numbers)*combinations(43,6-expected_number_of_winning_numbers)
    total_number_of_possible_outcomes = combinations(49,6)
    probability_of_getting_the_expected_number_of_winning_numbers = number_of_sucessful_outcomes / total_number_of_possible_outcomes
    probability_pct = probability_of_getting_the_expected_number_of_winning_numbers * 100
    print('''The chance of exactly getting {} of the winning numbers is {:.6f}%'''.format(expected_number_of_winning_numbers,probability_pct))

In [16]:
#testing the function
for i in range(2,6):
    probability_less_6(i)
    print('--------------------------')

The chance of exactly getting 2 of the winning numbers is 13.237803%
--------------------------
The chance of exactly getting 3 of the winning numbers is 1.765040%
--------------------------
The chance of exactly getting 4 of the winning numbers is 0.096862%
--------------------------
The chance of exactly getting 5 of the winning numbers is 0.001845%
--------------------------


# Getting atleast certain number of winning numbers on the ticket

In [17]:
def probability_atleast(min_expected_number_of_winning_numbers):
    number_of_sucessful_outcomes = combinations(6,min_expected_number_of_winning_numbers)*combinations(49-min_expected_number_of_winning_numbers,6-min_expected_number_of_winning_numbers)
    total_number_of_possible_outcomes = combinations(49,6)
    probability_of_getting_the_min_expected_number_of_winning_numbers = number_of_sucessful_outcomes / total_number_of_possible_outcomes
    probability_pct = probability_of_getting_the_min_expected_number_of_winning_numbers * 100
    print('''The chance of getting atleast {} of the winning numbers is {:.6f}%'''.format(min_expected_number_of_winning_numbers,probability_pct))

In [18]:
#testing the function
for i in range(2,6):
    probability_atleast(i)
    print('--------------------------')

The chance of getting atleast 2 of the winning numbers is 19.132653%
--------------------------
The chance of getting atleast 3 of the winning numbers is 2.171081%
--------------------------
The chance of getting atleast 4 of the winning numbers is 0.106194%
--------------------------
The chance of getting atleast 5 of the winning numbers is 0.001888%
--------------------------
